---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: invokeai
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/invokeai/deploy
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
