---
apiVersion: v1
kind: Namespace
metadata:
  name: invokeai

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invokeai
  namespace: invokeai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invokeai
  template:
    metadata:
      labels:
        app: invokeai
    spec:
      securityContext:
        fsGroup: 1101
      containers:
      - name: invokeai
        image: ghcr.io/thehonker/invokeai:rocm6.3-latest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1101
          runAsGroup: 1101
        ports:
        - containerPort: 9090
        resources:
          limits:
            hostdev.k8s.io/dev_kfd: 1
            hostdev.k8s.io/dev_dri_by-path_pci-0000_05_00.0-card: 1
            hostdev.k8s.io/dev_dri_by-path_pci-0000_05_00.0-render: 1
        env:
        - name: ROCR_VISIBLE_DEVICES
          value: "0"
        - name: HCC_AMDGPU_TARGET
          value: "gfx906"
        - name: HSA_OVERRIDE_GFX_VERSION
          value: "9.0.6"
        - name: INVOKEAI_HOST
          value: "0.0.0.0"
        - name: INVOKEAI_PORT
          value: "9090"
        - name: INVOKEAI_ROOT
          value: "/invokeai"
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: invokeai-hf-token
              key: token
        volumeMounts:
        - mountPath: "/invokeai"
          name: invokeai-data
      - name: alpine-debug
        image: docker.io/alpine:latest
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        command:
        - /bin/sh
        - -c
        - |
          tail -f /dev/null
        volumeMounts:
        - mountPath: "/invokeai"
          name: invokeai-data
      volumes:
      - name: invokeai-data
        persistentVolumeClaim:
          claimName: invokeai-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invokeai-data
  namespace: invokeai
spec:
  storageClassName: ssdpool-zfs
  resources:
    requests:
      storage: 128Gi
  accessModes:
  - ReadWriteOnce

---
apiVersion: v1
kind: Service
metadata:
  name: invokeai
  namespace: invokeai
spec:
  type: ClusterIP
  selector:
    app: invokeai
  ports:
  - name: "http"
    port: 9090
    targetPort: 9090

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: invokeai-your-domain
  namespace: invokeai
spec:
  commonName: invokeai.your.domain
  secretName: invokeai-your-domain-ingress-tls-cert
  dnsNames:
  - invokeai.your.domain
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: invokeai-your-domain
  namespace: invokeai
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`invokeai.your.domain`)
    middlewares:
    - name: authentik
      namespace: authentik
    services:
    - name: invokeai
      port: 9090
  tls:
    secretName: invokeai-your-domain-ingress-tls-cert
