# syntax=docker/dockerfile:1

FROM docker.io/node:22-slim AS web-builder
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack use pnpm@10.x && corepack enable

WORKDIR /build
COPY --chown=node:node ./invokeai/invokeai/frontend/web/ ./
RUN pnpm install --frozen-lockfile
RUN npx vite build

FROM docker.io/rocm/dev-ubuntu-24.04:6.3

SHELL ["/bin/bash", "-c"]

ARG GPU_DRIVER

ENV GPU_DRIVER=$GPU_DRIVER

USER root

RUN set -exu \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get -yq update \
  && apt-get -yq install \
    bash \
    bc \
    build-essential \
    cmake \
    curl \
    git \
    hipblas \
    hipblas-common-dev \
    hipblas-dev \
    hipblaslt \
    hiprand \
    hiprand-dev \
    hipsparse \
    hipsparse-dev \
    hipsparselt \
    hipsparselt-dev \
    libgl1 \
    libglib2.0-0 \
    libhipblas-dev \
    libhipblas0 \
    libhiprand-dev \
    libhiprand1 \
    libhipsparse-dev \
    libhipsparse0 \
    libopenblas-dev \
    libopenblas0 \
    libopenblas64-0 \
    libopenblas64-dev \
    libopencv-dev \
    libtcmalloc-minimal4 \
    make \
    nano \
    pciutils \
    pipx \
    python3 \
    python3-opencv \
    python3-pip \
    python3-setuptools \
    python3-venv \
    python3-wheel \
    rocm-utils \
    wget \
  && apt-get -yq clean \
  && rm -rf /var/lib/apt/lists/*

RUN set -exu \
  && addgroup \
    --gid 1101 \
    invokeai \
  && adduser \
    --uid 1101 \
    --ingroup invokeai \
    --disabled-password \
    --gecos invokeai \
    invokeai

# invokeai repo assumed to have been cloned for us
COPY ./entrypoint.sh /entrypoint.sh
COPY --chown=invokeai:invokeai ./invokeai /home/invokeai/invokeai-source
RUN set -exu && mkdir -pv /home/invokeai/invokeai-source/frontend/web/
COPY --from=web-builder --chown=invokeai:invokeai /build/dist /home/invokeai/invokeai-source/invokeai/frontend/web/dist
COPY --chown=invokeai:invokeai ./install-invokeai.sh /install-invokeai.sh

USER invokeai
WORKDIR /home/invokeai

RUN set -exu \
  && /bin/bash /install-invokeai.sh $GPU_DRIVER

USER root

RUN set -exu \
  && rm -rf $HOME/invokeai-source

USER invokeai

ENTRYPOINT ["/bin/bash"]
CMD ["/entrypoint.sh"]
