# syntax=docker/dockerfile:1

FROM docker.io/node:22-slim AS web-builder
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack use pnpm@10.x && corepack enable

WORKDIR /build
COPY --chown=node:node ./invokeai/invokeai/frontend/web/ ./
RUN pnpm install --frozen-lockfile
RUN npx vite build

FROM docker.io/rocm/dev-ubuntu-24.04:6.3

SHELL ["/bin/bash", "-c"]

ARG GPU_DRIVER

ENV GPU_DRIVER=$GPU_DRIVER

USER root

RUN set -exu \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get -yq update \
  && apt-get -yq install \
    bash \
    curl \
    nano \
    wget \
    git \
    python3 \
    python3-venv \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    python3-opencv \
    libopencv-dev \
    pipx \
    libgl1 \
    libglib2.0-0 \
    libtcmalloc-minimal4 \
    bc \
    pciutils \
    make \
    build-essential \
  && apt-get -yq clean

RUN set -exu \
  && addgroup \
    --gid 1101 \
    invokeai \
  && adduser \
    --uid 1101 \
    --ingroup invokeai \
    --disabled-password \
    --gecos invokeai \
    invokeai \
  && usermod -a -G render invokeai

# invokeai repo assumed to have been cloned for us
COPY ./entrypoint.sh /entrypoint.sh
COPY --chown=invokeai:invokeai ./invokeai /home/invokeai/invokeai-source
RUN set -exu && mkdir -pv /home/invokeai/invokeai-source/frontend/web/
COPY --from=web-builder --chown=invokeai:invokeai /build/dist /home/invokeai/invokeai-source/invokeai/frontend/web/dist
COPY --chown=invokeai:invokeai ./install-invokeai.sh /install-invokeai.sh

USER invokeai
WORKDIR /home/invokeai

RUN set -exu \
  && /bin/bash /install-invokeai.sh $GPU_DRIVER

USER root

RUN set -exu \
  && rm -rf $HOME/invokeai-source

USER invokeai

ENTRYPOINT ["/bin/bash"]
CMD ["/entrypoint.sh"]
