name: InvokeAI - CUDA 13.0.x - Nightly
on:
  push:
    branches:
      - main
  schedule:
    # 00:00 on Sunday
    - cron: "0 0 * * *"
  workflow_dispatch: {}

concurrency:
  group: "invokeai-nightly-cu130"
  cancel-in-progress: false

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/container-image-ci-base.yml
    with:
      gpu-driver: cu130
      build-type: hash
