name: InvokeAI Docker Image Build - CUDA 13.0.x - Stable
on:
  push:
    branches:
      - main
  schedule:
    # 00:00 on Sunday
    - cron: "0 0 * * 0"
  workflow_dispatch: {}

concurrency:
  group: "invokeai-weekly-cu130"
  cancel-in-progress: false

jobs:
  build-and-push:
    uses: ./.github/workflows/container-image-ci-base.yml
    with:
      gpu-driver: cu130
      build-type: tag
