name: InvokeAI Docker Image Build - CPU - Stable
on:
  push:
    branches:
      - main
  schedule:
    # 00:00 on Sunday
    - cron: "0 0 * * 0"
  workflow_dispatch: {}

concurrency:
  group: "invokeai-stable-cpu"
  cancel-in-progress: false

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/container-image-ci-base.yml
    with:
      gpu-driver: cpu
      build-type: tag
