name: InvokeAI - CUDA 12.6.x - Stable
on:
  push:
    branches:
      - main
  schedule:
    # 00:00 on Sunday
    - cron: "0 0 * * 0"
  workflow_dispatch: {}

concurrency:
  group: "invokeai-weekly-cu126"
  cancel-in-progress: true

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/container-image-ci-base.yml
    with:
      gpu-driver: cu126
      build-type: tag
